base_url = "https://termania.dev"
title = "Termania"
description = "GPU-accelerated multi-pane terminal emulator"
compile_sass = false
build_search_index = false

[markdown]
highlight_code = true
highlight_theme = "base16-ocean-dark"
